# -*- coding: utf-8 -*-
"""
/***************************************************************************
 geosampa_api
                                 A QGIS plugin
 Cria a conexão entre o Geosampa e o QGIS
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-06-25
        copyright            : (C) 2019 by Thomas
        email                : -
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load geosampa_api class from file geosampa_api.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Geosampa_api import geosampa_api
    return geosampa_api(iface)
