# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'geosampa_api_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_GEOSAMPA_apiDialogBase(object):
    def setupUi(self, GEOSAMPA_apiDialogBase):
        GEOSAMPA_apiDialogBase.setObjectName("GEOSAMPA_apiDialogBase")
        GEOSAMPA_apiDialogBase.setWindowModality(QtCore.Qt.NonModal)
        GEOSAMPA_apiDialogBase.resize(738, 312)
        self.textBrowser = QtWidgets.QTextBrowser(GEOSAMPA_apiDialogBase)
        self.textBrowser.setGeometry(QtCore.QRect(462, 9, 266, 291))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser.sizePolicy().hasHeightForWidth())
        self.textBrowser.setSizePolicy(sizePolicy)
        self.textBrowser.setMinimumSize(QtCore.QSize(266, 0))
        self.textBrowser.setAutoFillBackground(False)
        self.textBrowser.setObjectName("textBrowser")
        self.button_box = QtWidgets.QDialogButtonBox(GEOSAMPA_apiDialogBase)
        self.button_box.setGeometry(QtCore.QRect(290, 280, 156, 23))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.label = QtWidgets.QLabel(GEOSAMPA_apiDialogBase)
        self.label.setGeometry(QtCore.QRect(20, 10, 153, 24))
        font = QtGui.QFont()
        font.setFamily("Museo 700")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label.setFont(font)
        self.label.setMouseTracking(False)
        self.label.setAcceptDrops(False)
        self.label.setObjectName("label")
        self.splitter_2 = QtWidgets.QSplitter(GEOSAMPA_apiDialogBase)
        self.splitter_2.setGeometry(QtCore.QRect(20, 122, 421, 41))
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.camada_2 = QtWidgets.QLabel(self.splitter_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.camada_2.sizePolicy().hasHeightForWidth())
        self.camada_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Museo 500")
        font.setPointSize(9)
        self.camada_2.setFont(font)
        self.camada_2.setObjectName("camada_2")
        self._camada = QtWidgets.QComboBox(self.splitter_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._camada.sizePolicy().hasHeightForWidth())
        self._camada.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self._camada.setFont(font)
        self._camada.setObjectName("_camada")
        self.splitter = QtWidgets.QSplitter(GEOSAMPA_apiDialogBase)
        self.splitter.setGeometry(QtCore.QRect(20, 60, 421, 41))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.camada = QtWidgets.QLabel(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.camada.sizePolicy().hasHeightForWidth())
        self.camada.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Museo 500")
        font.setPointSize(9)
        self.camada.setFont(font)
        self.camada.setObjectName("camada")
        self._tema = QtWidgets.QComboBox(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._tema.sizePolicy().hasHeightForWidth())
        self._tema.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self._tema.setFont(font)
        self._tema.setObjectName("_tema")
        self.splitter_5 = QtWidgets.QSplitter(GEOSAMPA_apiDialogBase)
        self.splitter_5.setGeometry(QtCore.QRect(20, 192, 421, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_5.sizePolicy().hasHeightForWidth())
        self.splitter_5.setSizePolicy(sizePolicy)
        self.splitter_5.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_5.setObjectName("splitter_5")
        self.splitter_3 = QtWidgets.QSplitter(self.splitter_5)
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName("splitter_3")
        self.camada_3 = QtWidgets.QLabel(self.splitter_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.camada_3.sizePolicy().hasHeightForWidth())
        self.camada_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Museo 500")
        font.setPointSize(9)
        self.camada_3.setFont(font)
        self.camada_3.setObjectName("camada_3")
        self._formato = QtWidgets.QComboBox(self.splitter_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self._formato.setFont(font)
        self._formato.setObjectName("_formato")
        self.splitter_4 = QtWidgets.QSplitter(self.splitter_5)
        self.splitter_4.setOrientation(QtCore.Qt.Vertical)
        self.splitter_4.setObjectName("splitter_4")
        self.camada_4 = QtWidgets.QLabel(self.splitter_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.camada_4.sizePolicy().hasHeightForWidth())
        self.camada_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Museo 500")
        font.setPointSize(9)
        self.camada_4.setFont(font)
        self.camada_4.setObjectName("camada_4")
        self._datum = QtWidgets.QComboBox(self.splitter_4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self._datum.setFont(font)
        self._datum.setObjectName("_datum")

        self.retranslateUi(GEOSAMPA_apiDialogBase)
        self.button_box.accepted.connect(GEOSAMPA_apiDialogBase.accept)
        self.button_box.rejected.connect(GEOSAMPA_apiDialogBase.reject)
        QtCore.QMetaObject.connectSlotsByName(GEOSAMPA_apiDialogBase)

    def retranslateUi(self, GEOSAMPA_apiDialogBase):
        _translate = QtCore.QCoreApplication.translate
        GEOSAMPA_apiDialogBase.setWindowTitle(_translate("GEOSAMPA_apiDialogBase", "GEOSAMPA api"))
        self.textBrowser.setHtml(_translate("GEOSAMPA_apiDialogBase", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/newPrefix/resources/spurbanismo-color-small.png\" /></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'museo 300\'; font-size:11pt; font-weight:600; color:#4d4d4d;\">OBJETIVO</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'museo 300\';\">Visa facilitar a obtenção dos dados geográficos da cidade de São Paulo, de forma a agilizar o trabalho de servidores públicos, pesquisadores e cidadãos na observação de dados da cidades. Por meio da facilitação, através do uso de API, é possível conectar o dados abertos do GeoSampa com a plataforma do QGIS.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'museo 300\'; font-weight:600; color:#5f5f5f;\">Reportar erro:</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'museo 300\'; font-size:7pt; font-weight:600; color:#5f5f5f;\">Gitbub: </span><a href=\"https://github.com/yubathom/api-geosampa\"><span style=\" font-family:\'museo 300\'; font-size:8pt; text-decoration: underline; color:#0000ff;\">https://github.com/yubathom/api-geosampa</span></a></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'museo 300\'; font-size:7pt; font-weight:600; color:#5f5f5f;\">Email: </span><span style=\" font-family:\'museo 300\'; font-size:7pt; color:#5f5f5f;\">tlyuba@spurbanismo.sp.gov.br</span></p></body></html>"))
        self.label.setText(_translate("GEOSAMPA_apiDialogBase", "GeoSampa - API"))
        self.camada_2.setText(_translate("GEOSAMPA_apiDialogBase", "CAMADA"))
        self.camada.setText(_translate("GEOSAMPA_apiDialogBase", "TEMA"))
        self.camada_3.setText(_translate("GEOSAMPA_apiDialogBase", "FORMATO"))
        self.camada_4.setText(_translate("GEOSAMPA_apiDialogBase", "DATUM"))

